# Generated by Django 5.1.4 on 2024-12-29 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_type', models.CharField(choices=[('normal', '일반 적'), ('hunt', '사냥몹'), ('boss', '보스')], default='normal', max_length=10)),
                ('hp', models.IntegerField(default=10)),
                ('max_hp', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=0)),
                ('shield', models.IntegerField(default=0)),
                ('is_dead', models.BooleanField(default=False)),
                ('current_zone', models.CharField(choices=[('myzone', '내 구역'), ('hunt', '사냥터'), ('boss', '보스존')], default='myzone', max_length=20)),
                ('spawn_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='summonedball',
            name='session',
        ),
        migrations.RemoveField(
            model_name='summonedball',
            name='user',
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', '빨강'), ('orange', '주황'), ('yellow', '노랑'), ('green', '초록'), ('blue', '파랑'), ('navy', '남색'), ('purple', '보라')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', '커먼'), ('uncommon', '언커먼'), ('normal', '노멀'), ('rare', '레어'), ('epic', '에픽'), ('unique', '유니크'), ('legendary', '레전더리'), ('immortal', '임모탈')], max_length=20)),
                ('base_damage', models.IntegerField(default=1)),
                ('base_attack_speed', models.FloatField(default=1.0)),
                ('special_option', models.CharField(blank=True, max_length=100, null=True)),
                ('current_zone', models.CharField(choices=[('myzone', '내 구역'), ('hunt', '사냥터'), ('boss', '보스존')], default='myzone', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ColorUpgrade',
        ),
        migrations.DeleteModel(
            name='SummonedBall',
        ),
    ]
