# Generated by Django 5.1.4 on 2025-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_enemy_remove_summonedball_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('weight', models.IntegerField(default=1)),
                ('base_damage', models.IntegerField(default=1)),
                ('base_attack_speed', models.FloatField(default=1.0)),
                ('special_option', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enemy_type', models.CharField(choices=[('normal', '일반'), ('hunt', '사냥몹'), ('boss', '보스')], max_length=10)),
                ('hp', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=0)),
                ('shield', models.IntegerField(default=0)),
                ('stage_min', models.IntegerField(default=1)),
                ('stage_max', models.IntegerField(default=999)),
            ],
        ),
        migrations.RemoveField(
            model_name='ball',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enemy',
        ),
        migrations.DeleteModel(
            name='Ball',
        ),
    ]
